[2024-09-13 18:00:12,789] 17 root - INFO - data loading started...
[2024-09-13 18:00:12,790] 23 root - INFO - exception in loading data...
[2024-09-13 18:01:02,934] 17 root - INFO - data loading started...
[2024-09-13 18:01:02,936] 23 root - INFO - exception in loading data...
[2024-09-13 18:01:12,628] 17 root - INFO - data loading started...
[2024-09-13 18:01:12,628] 23 root - INFO - exception in loading data...
[2024-09-13 18:01:45,181] 17 root - INFO - data loading started...
[2024-09-13 18:01:45,182] 23 root - INFO - exception in loading data...
[2024-09-13 18:01:59,550] 17 root - INFO - data loading started...
[2024-09-13 18:01:59,550] 23 root - INFO - exception in loading data...
[2024-09-13 18:02:01,462] 17 root - INFO - data loading started...
[2024-09-13 18:02:01,464] 23 root - INFO - exception in loading data...
[2024-09-13 18:02:10,240] 17 root - INFO - data loading started...
[2024-09-13 18:02:10,864] 160 numexpr.utils - INFO - NumExpr defaulting to 8 threads.
[2024-09-13 18:02:11,477] 20 root - INFO - data loading completed...
[2024-09-13 18:02:14,484] 142 google.auth.compute_engine._metadata - WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
[2024-09-13 18:02:18,569] 142 google.auth.compute_engine._metadata - WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out
[2024-09-13 18:02:20,744] 142 google.auth.compute_engine._metadata - WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 64] Host is down
[2024-09-13 18:02:20,744] 338 google.auth._default - WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2024-09-13 18:03:20,088] 17 root - INFO - data loading started...
[2024-09-13 18:03:20,090] 20 root - INFO - data loading completed...
[2024-09-13 18:03:21,807] 21 root - INFO - 
[2024-09-13 18:05:35,093] 17 root - INFO - data loading started...
[2024-09-13 18:05:35,096] 20 root - INFO - data loading completed...
[2024-09-13 18:05:36,770] 21 root - INFO - 
[2024-09-13 18:05:40,551] 142 google.auth.compute_engine._metadata - WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
[2024-09-13 18:05:44,621] 142 google.auth.compute_engine._metadata - WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out
[2024-09-13 18:05:46,554] 142 google.auth.compute_engine._metadata - WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 64] Host is down
[2024-09-13 18:05:46,554] 338 google.auth._default - WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2024-09-13 18:06:08,685] 18 root - INFO - data loading started...
[2024-09-13 18:06:08,689] 21 root - INFO - data loading completed...
[2024-09-13 18:06:10,254] 22 root - INFO - 
[2024-09-13 18:06:13,289] 142 google.auth.compute_engine._metadata - WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
[2024-09-13 18:06:17,246] 142 google.auth.compute_engine._metadata - WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out
[2024-09-13 18:06:19,303] 142 google.auth.compute_engine._metadata - WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 64] Host is down
[2024-09-13 18:06:19,303] 338 google.auth._default - WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2024-09-13 18:06:27,127] 18 root - INFO - data loading started...
[2024-09-13 18:06:27,130] 21 root - INFO - data loading completed...
[2024-09-13 18:06:28,687] 22 root - INFO - 
[2024-09-13 18:06:28,720] 142 google.auth.compute_engine._metadata - WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 64] Host is down
[2024-09-13 18:06:29,765] 142 google.auth.compute_engine._metadata - WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 64] Host is down
[2024-09-13 18:06:31,647] 142 google.auth.compute_engine._metadata - WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 64] Host is down
[2024-09-13 18:06:31,648] 338 google.auth._default - WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2024-09-13 18:07:25,366] 18 root - INFO - data loading started...
[2024-09-13 18:07:25,369] 21 root - INFO - data loading completed...
[2024-09-13 18:07:27,054] 23 root - INFO - 
[2024-09-13 18:07:30,088] 142 google.auth.compute_engine._metadata - WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
[2024-09-13 18:07:34,115] 142 google.auth.compute_engine._metadata - WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out
[2024-09-13 18:07:36,227] 142 google.auth.compute_engine._metadata - WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 64] Host is down
[2024-09-13 18:07:36,227] 338 google.auth._default - WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2024-09-13 18:14:45,388] 18 root - INFO - data loading started...
[2024-09-13 18:14:45,395] 21 root - INFO - data loading completed...
[2024-09-13 18:14:46,990] 32 root - INFO - 
[2024-09-13 18:14:50,039] 142 google.auth.compute_engine._metadata - WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
[2024-09-13 18:14:54,088] 142 google.auth.compute_engine._metadata - WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out
[2024-09-13 18:14:56,289] 142 google.auth.compute_engine._metadata - WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 64] Host is down
[2024-09-13 18:14:56,289] 338 google.auth._default - WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2024-09-13 19:25:49,602] 18 root - INFO - data loading started...
[2024-09-13 19:25:49,647] 21 root - INFO - data loading completed...
[2024-09-13 19:25:51,316] 32 root - INFO - 
[2024-09-13 19:25:54,382] 142 google.auth.compute_engine._metadata - WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
[2024-09-13 19:25:58,466] 142 google.auth.compute_engine._metadata - WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out
[2024-09-13 19:26:00,519] 142 google.auth.compute_engine._metadata - WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 64] Host is down
[2024-09-13 19:26:00,520] 338 google.auth._default - WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2024-09-13 19:31:25,968] 18 root - INFO - data loading started...
[2024-09-13 19:31:25,981] 21 root - INFO - data loading completed...
[2024-09-13 19:31:27,694] 32 root - INFO - 
[2024-09-13 19:31:30,747] 142 google.auth.compute_engine._metadata - WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
[2024-09-13 19:31:34,669] 142 google.auth.compute_engine._metadata - WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out
[2024-09-13 19:31:36,809] 142 google.auth.compute_engine._metadata - WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 64] Host is down
[2024-09-13 19:31:36,810] 338 google.auth._default - WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2024-09-13 19:42:22,226] 18 root - INFO - data loading started...
[2024-09-13 19:42:22,237] 21 root - INFO - data loading completed...
[2024-09-13 19:43:11,856] 18 root - INFO - data loading started...
[2024-09-13 19:43:11,860] 21 root - INFO - data loading completed...
[2024-09-13 19:43:13,430] 34 root - INFO - 
[2024-09-13 19:43:13,432] 41 root - INFO - 
[2024-09-13 19:44:05,983] 18 root - INFO - data loading started...
[2024-09-13 19:44:05,984] 21 root - INFO - data loading completed...
[2024-09-13 19:44:07,598] 34 root - INFO - 
[2024-09-13 19:44:07,601] 41 root - INFO - 
[2024-09-13 19:44:10,641] 142 google.auth.compute_engine._metadata - WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
[2024-09-13 19:44:14,663] 142 google.auth.compute_engine._metadata - WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out
[2024-09-13 19:44:16,595] 142 google.auth.compute_engine._metadata - WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 64] Host is down
[2024-09-13 19:44:16,596] 338 google.auth._default - WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2024-09-13 19:48:27,212] 18 root - INFO - data loading started...
[2024-09-13 19:48:27,220] 21 root - INFO - data loading completed...
[2024-09-13 19:48:28,928] 34 root - INFO - 
[2024-09-13 19:48:28,931] 41 root - INFO - 
[2024-09-13 19:49:14,594] 18 root - INFO - data loading started...
[2024-09-13 19:49:14,596] 21 root - INFO - data loading completed...
[2024-09-13 19:49:16,125] 34 root - INFO - 
[2024-09-13 19:49:16,127] 41 root - INFO - 
[2024-09-13 19:51:36,532] 18 root - INFO - data loading started...
[2024-09-13 19:51:36,537] 21 root - INFO - data loading completed...
[2024-09-13 19:51:38,155] 35 root - INFO - 
[2024-09-13 19:52:14,479] 18 root - INFO - data loading started...
[2024-09-13 19:52:14,481] 21 root - INFO - data loading completed...
[2024-09-13 19:52:14,865] 34 root - INFO - 
[2024-09-13 19:52:14,867] 41 root - INFO - 
[2024-09-13 19:54:02,649] 18 root - INFO - data loading started...
[2024-09-13 19:54:02,652] 21 root - INFO - data loading completed...
[2024-09-13 19:54:04,278] 34 root - INFO - 
[2024-09-13 19:54:04,280] 41 root - INFO - 
[2024-09-13 19:56:31,026] 18 root - INFO - data loading started...
[2024-09-13 19:56:31,033] 21 root - INFO - data loading completed...
[2024-09-13 19:56:31,505] 34 root - INFO - 
[2024-09-13 19:56:31,507] 41 root - INFO - 
[2024-09-13 19:59:03,966] 18 root - INFO - data loading started...
[2024-09-13 19:59:03,969] 21 root - INFO - data loading completed...
[2024-09-13 19:59:04,574] 30 root - INFO - Initializing embedding model...
[2024-09-13 19:59:04,576] 40 root - INFO - Creating VectorStoreIndex...
[2024-09-13 19:59:07,891] 18 root - INFO - data loading started...
[2024-09-13 19:59:07,892] 21 root - INFO - data loading completed...
[2024-09-13 19:59:09,387] 30 root - INFO - Initializing embedding model...
[2024-09-13 19:59:09,405] 40 root - INFO - Creating VectorStoreIndex...
[2024-09-13 19:59:41,923] 18 root - INFO - data loading started...
[2024-09-13 19:59:41,925] 21 root - INFO - data loading completed...
[2024-09-13 20:00:26,714] 18 root - INFO - data loading started...
[2024-09-13 20:00:26,717] 21 root - INFO - data loading completed...
[2024-09-13 20:00:28,395] 30 root - INFO - Initializing embedding model...
[2024-09-13 20:00:28,398] 40 root - INFO - Creating VectorStoreIndex...
[2024-09-13 20:02:08,041] 18 root - INFO - data loading started...
[2024-09-13 20:02:08,060] 21 root - INFO - data loading completed...
[2024-09-13 20:02:09,664] 30 root - INFO - Initializing embedding model...
[2024-09-13 20:02:09,667] 40 root - INFO - Creating VectorStoreIndex...
[2024-09-13 20:03:40,934] 18 root - INFO - data loading started...
[2024-09-13 20:03:40,941] 21 root - INFO - data loading completed...
[2024-09-13 20:03:42,651] 30 root - INFO - Initializing embedding model...
[2024-09-13 20:03:42,653] 34 root - INFO - Type of gemini_embed_model: <class 'llama_index.embeddings.gemini.base.GeminiEmbedding'>
[2024-09-13 20:03:42,655] 38 root - INFO - Type of node_parser: <class 'llama_index.core.node_parser.text.sentence.SentenceSplitter'>
[2024-09-13 20:03:42,655] 41 root - INFO - Type of documents: <class 'list'>
[2024-09-13 20:03:42,655] 44 root - INFO - Number of documents: 1
[2024-09-13 20:03:42,655] 46 root - INFO - Creating VectorStoreIndex...
[2024-09-13 20:03:42,658] 67 root - ERROR - Exception occurred: 'tuple' object is not callable
Traceback (most recent call last):
  File "/Users/aishu/Desktop/RAG/QAWithPDF/embedding.py", line 49, in download_gemini_embedding
    index = VectorStoreIndex.from_documents(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/llama_index/core/indices/base.py", line 112, in from_documents
    nodes = run_transformations(
            ^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/llama_index/core/ingestion/pipeline.py", line 100, in run_transformations
    nodes = transform(nodes, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'tuple' object is not callable
[2024-09-13 20:04:44,114] 18 root - INFO - data loading started...
[2024-09-13 20:04:44,117] 21 root - INFO - data loading completed...
[2024-09-13 20:04:45,760] 34 root - INFO - 
[2024-09-13 20:04:45,762] 41 root - INFO - 
[2024-09-13 20:06:28,520] 18 root - INFO - data loading started...
[2024-09-13 20:06:28,523] 21 root - INFO - data loading completed...
[2024-09-13 20:06:30,724] 34 root - INFO - 
[2024-09-13 20:06:30,725] 40 root - INFO - 
[2024-09-13 20:09:27,866] 18 root - INFO - data loading started...
[2024-09-13 20:09:27,874] 21 root - INFO - data loading completed...
[2024-09-13 20:09:29,468] 34 root - INFO - 
[2024-09-13 20:09:29,470] 40 root - INFO - 
[2024-09-13 20:13:15,547] 18 root - INFO - data loading started...
[2024-09-13 20:13:15,550] 21 root - INFO - data loading completed...
[2024-09-13 20:13:17,120] 34 root - INFO - 
[2024-09-13 20:13:17,120] 40 root - INFO - 
[2024-09-13 20:13:36,082] 18 root - INFO - data loading started...
[2024-09-13 20:13:36,085] 21 root - INFO - data loading completed...
[2024-09-13 20:13:37,722] 34 root - INFO - 
[2024-09-13 20:13:37,723] 40 root - INFO - 
[2024-09-13 20:13:57,850] 18 root - INFO - data loading started...
[2024-09-13 20:13:57,853] 21 root - INFO - data loading completed...
[2024-09-13 20:13:59,430] 34 root - INFO - 
[2024-09-13 20:13:59,430] 40 root - INFO - 
[2024-09-13 20:16:33,704] 18 root - INFO - data loading started...
[2024-09-13 20:16:33,710] 21 root - INFO - data loading completed...
[2024-09-13 20:16:35,350] 34 root - INFO - 
[2024-09-13 20:16:35,351] 40 root - INFO - 
[2024-09-13 20:17:07,916] 18 root - INFO - data loading started...
[2024-09-13 20:17:07,918] 21 root - INFO - data loading completed...
[2024-09-13 20:17:08,307] 34 root - INFO - 
[2024-09-13 20:17:08,307] 40 root - INFO - 
[2024-09-13 20:17:14,240] 18 root - INFO - data loading started...
[2024-09-13 20:17:14,244] 21 root - INFO - data loading completed...
[2024-09-13 20:17:14,625] 34 root - INFO - 
[2024-09-13 20:17:14,626] 40 root - INFO - 
[2024-09-13 20:17:15,108] 18 root - INFO - data loading started...
[2024-09-13 20:17:15,111] 21 root - INFO - data loading completed...
[2024-09-13 20:17:16,633] 34 root - INFO - 
[2024-09-13 20:17:16,633] 40 root - INFO - 
[2024-09-13 20:17:30,625] 18 root - INFO - data loading started...
[2024-09-13 20:17:30,628] 21 root - INFO - data loading completed...
[2024-09-13 20:17:32,199] 34 root - INFO - 
[2024-09-13 20:17:32,199] 40 root - INFO - 
[2024-09-13 20:19:40,071] 18 root - INFO - data loading started...
[2024-09-13 20:19:40,074] 21 root - INFO - data loading completed...
[2024-09-13 20:19:41,734] 34 root - INFO - 
[2024-09-13 20:19:41,735] 40 root - INFO - 
[2024-09-13 20:19:44,783] 142 google.auth.compute_engine._metadata - WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
[2024-09-13 20:19:48,860] 142 google.auth.compute_engine._metadata - WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out
[2024-09-13 20:19:50,879] 142 google.auth.compute_engine._metadata - WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 64] Host is down
[2024-09-13 20:19:50,879] 338 google.auth._default - WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2024-09-14 22:51:50,606] 18 root - INFO - data loading started...
[2024-09-14 22:51:50,622] 21 root - INFO - data loading completed...
[2024-09-14 22:51:52,280] 34 root - INFO - 
[2024-09-14 22:51:52,282] 40 root - INFO - 
[2024-09-14 22:51:55,430] 142 google.auth.compute_engine._metadata - WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
[2024-09-14 22:51:59,385] 142 google.auth.compute_engine._metadata - WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out
[2024-09-14 22:52:01,541] 142 google.auth.compute_engine._metadata - WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 64] Host is down
[2024-09-14 22:52:01,542] 338 google.auth._default - WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
